version: '3.8'

services:
  web:
    build: ./docker
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_NAME: todoapp
      DB_USER: admin
      DB_PASS: secret123
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
